<a href="https://colab.research.google.com/github/yunhatsal/py/blob/main/CTAB_7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. 일한시간과 시급을 계산하여 출력하는 코드
- 일한시간(hours_worked)
- 일한날짜(day_worked)
- 시급(pay_rate)
- 월급(monthly_pay)

In [ ]:
hours_worked = int(input("일한 시간을 입력하시오.: "))  # 일한 시간을 입력받습니다.
pay_rate = int(input("시급을 입력하시오.(23년 시급 9620): "))   # 시급을 입력받습니다. (23년 시급 9620)
day_worked = int(input("일한 날짜를 입력하시오.: "))  # 일한 날짜를 입력받습니다.
day_month = hours_worked * day_worked   # 월별 총 근무 시간을 계산합니다. (일한 시간 * 일한 날짜)
monthly_pay = hours_worked * pay_rate * day_worked  # 월급여를 계산합니다. (일한 시간 * 시급 * 일한 날짜)
print(f'일한 시간은 {hours_worked}시간이며, 시급은 {pay_rate}원이고, 월급여는 {monthly_pay}원입니다.')  # 결과를 출력합니다.


일한 시간을 입력하시오.: 10
시급을 입력하시오.(23년 시급 9620): 9620
일한 날짜를 입력하시오.: 25
일한 시간은 10시간이며, 시급은 9620원이고, 월급여는 2405000원입니다.


이 코드는 사용자로부터 일한 시간, 시급, 일한 날짜를 입력받아서 월급여를 계산하고 출력합니다. 예를 들어, 사용자가 일한 시간으로 8시간, 시급으로 9620원, 일한 날짜로 20일을 입력했다면, 월급여는 8 * 9620 * 20 = 1,539,200원이 됩니다. 마지막으로 결과를 출력할 때는 f-string을 사용하여 변수의 값을 문자열에 삽입하였습니다.

이렇게 코드를 작성하면 사용자가 일한 시간, 시급, 일한 날짜를 입력하면 월급여를 계산하여 출력할 수 있습니다.

2. 환전하는 코드를 작성
- 변수 won, usd, exchange
- 계산 won * usd

In [ ]:
usd = int(input("환전할 달러를 입력: "))  # 환전할 달러를 입력받습니다.
won = int(input("달러의 환율금액 입력(231031: 1372원)"))  # 달러의 환율금액을 입력받습니다. (231031: 1372원)
exchange = won * usd  # 환전 금액을 계산합니다. (환율 * 달러)
print(f'환전하고 싶은 {usd}달러는 환율 {won}으로 계산해서, {exchange}원입니다.')   # 결과를 출력합니다.


환전할 달러를 입력: 500
달러의 환율금액 입력(231031: 1372원)1372
환전하고 싶은 500달러는 환율 1372으로 계산해서, 686000원입니다.


이 코드는 사용자로부터 환전할 달러와 달러의 환율금액을 입력받아서 해당 금액을 원화로 환전하고 결과를 출력합니다. 예를 들어, 사용자가 환전할 달러로 100달러, 환율으로 1372원을 입력했다면, 환전 금액은 100 * 1372 = 137,200원이 됩니다. 마지막으로 결과를 출력할 때는 f-string을 사용하여 변수의 값을 문자열에 삽입하였습니다.

이렇게 코드를 작성하면 사용자가 환전할 달러와 환율을 입력하면 해당 금액을 원화로 환전하여 출력할 수 있습니다.

3. 화씨를 섭씨로, 섭씨를 화씨로 변경하는 코드
- 화씨를 섭씨로 ℉ = ℃ * 1.8 + 32
- 섭씨를 화씨로 ℃ = (℉- 32) / 1.8
- 변수 화씨 fahrenheit, 섭씨 celsius

In [ ]:
fahrenheit = int(input("화씨를 입력하시오.: "))   # 화씨 온도를 입력받습니다.
celsius = (fahrenheit - 32) / 1.8   # 화씨를 섭씨로 변환하여 계산합니다. (화씨 - 32) / 1.8
print(celsius)  # 섭씨 온도를 출력합니다.

화씨를 입력하시오.: 100
37.77777777777778


이 코드는 사용자로부터 화씨 온도를 입력받아서 해당 온도를 섭씨 온도로 변환하고 출력합니다. 화씨를 섭씨로 변환하기 위해서는 화씨에서 32를 빼고 1.8로 나누면 됩니다. 예를 들어, 사용자가 화씨 온도로 95를 입력했다면, 섭씨 온도는 (95 - 32) / 1.8 = 35입니다.

이렇게 코드를 작성하면 사용자가 화씨 온도를 입력하면 해당 온도를 섭씨 온도로 변환하여 출력할 수 있습니다.

In [ ]:
celsius = float(input("섭씨를 입력하시오.: "))  # 섭씨 온도를 입력받습니다.
fahrenheit = celsius * 1.8 + 32   # 섭씨를 화씨로 변환하여 계산합니다. (섭씨 * 1.8 + 32)
print(fahrenheit)   # 화씨 온도를 출력합니다.

섭씨를 입력하시오.: 37.77777777777778
100.0


이 코드는 사용자로부터 섭씨 온도를 입력받아서 해당 온도를 화씨 온도로 변환하고 출력합니다. 섭씨를 화씨로 변환하기 위해서는 섭씨에 1.8을 곱하고 32를 더하면 됩니다. 예를 들어, 사용자가 섭씨 온도로 25를 입력했다면, 화씨 온도는 25 * 1.8 + 32 = 77입니다.

이렇게 코드를 작성하면 사용자가 섭씨 온도를 입력하면 해당 온도를 화씨 온도로 변환하여 출력할 수 있습니다.